import { registerTranslations } from "./i18n.js";

registerTranslations({
  en: {
    serviceCommon: {
      nav: { home: "Home", overview: "Service", audience: "Audience", process: "Process", contact: "Contact" },
      breadcrumb: { services: "Services", residential: "Residential electrical design" },
      credential: {
        label: "Professional identification",
        status: "Controlled availability",
        title: "Electrical Engineer",
        creaLabel: "CREA-SP",
        creaValue: "5071811903",
        baseLabel: "Base",
        baseValue: "Jundiaí / SP",
        scopeLabel: "Initial scope",
        scopeValue: "Design only",
        deliveryLabel: "Format",
        deliveryValue: "Technical documentation + design ART"
      },
      actions: { scope: "Request a scope review", scenarios: "Choose your situation", general: "View the general service" },
      footer: { tagline: "Residential electrical design with defined scope, documented decisions, and technical responsibility." }
    },
    residentialService: {
      general: {
        meta: {
          title: "Residential Electrical Design in Jundiaí — Adrian Batista",
          description: "Residential electrical design for construction and renovation in Jundiaí, with circuits, loads, protection, documentation, and design ART."
        },
        hero: {
          eyebrow: "Residential electrical design · Jundiaí / SP",
          title: "A clear design for execution without improvisation.",
          lead: "Planning of loads, circuits, conductors, protection devices, and switchboards, delivered as technical documentation for the installation team and accompanied by a design ART."
        },
        audience: {
          kicker: "Choose the correct path", title: "Different decisions require different starting points.", intro: "Select the page closest to your situation. Each version explains the inputs, responsibilities, and next step without changing the technical scope.",
          partner: { title: "Architects and construction professionals", desc: "Compatibility checkpoints, input documents, handoff, and communication with the design team.", label: "Professional partnership" },
          construction: { title: "New construction or major renovation", desc: "What must be decided before execution, what the design contains, and how changes are controlled.", label: "Homeowner in planning" },
          loads: { title: "Planned new electrical loads", desc: "Technical screening for equipment that may require new circuits, protection, or a capacity review.", label: "Capacity and new circuits" }
        },
        deliverables: {
          kicker: "Technical output", title: "What the design organizes", intro: "The final package is defined by proposal. The items below form the reference scope for a low-complexity residence with stable architectural information.",
          items: {
            0: { title: "Points and circuits", desc: "Allocation of electrical points and circuit grouping consistent with the approved use of each space." },
            1: { title: "Load schedule", desc: "Organized loads, demand assumptions, circuit identification, and switchboard information." },
            2: { title: "Conductors and protection", desc: "Technical dimensioning of conductors and protection devices according to the applicable design criteria." },
            3: { title: "Diagrams", desc: "Single-line diagrams and details needed to interpret the design during execution." },
            4: { title: "Technical notes", desc: "Specifications, assumptions, and execution notes that prevent decisions from remaining implicit." },
            5: { title: "Design ART", desc: "Record of Adrian's technical responsibility for the activities effectively contracted and developed." }
          }
        },
        process: {
          kicker: "Workflow", title: "A controlled sequence before drawing", intro: "The design begins only after the scope, inputs, schedule, contract, and technical responsibility are aligned.",
          items: {
            0: { title: "Scope screening", desc: "Property type, current stage, architectural files, location, loads, and expected decisions." },
            1: { title: "Proposal and inputs", desc: "Deliverables, exclusions, schedule, reviews, fees, and required documents are formalized." },
            2: { title: "Design and review", desc: "Technical development in AutoCAD, internal checks, and defined compatibility milestones." },
            3: { title: "Delivery and guidance", desc: "Final files, design ART, recorded assumptions, and an orientation meeting for the handoff." }
          }
        },
        boundaries: {
          kicker: "Responsibility boundaries", title: "Design and execution are different services.", intro: "The page does not sell emergency work, isolated signatures, or undocumented approval promises.",
          includedTitle: "Initial offer", included: { 0: "Residential electrical design with defined inputs", 1: "Technical documentation for execution", 2: "Design ART within the contracted scope", 3: "One active project at a time" },
          excludedTitle: "Not included by default", excluded: { 0: "Installation labor or material purchasing", 1: "Responsibility for third-party execution", 2: "Emergency repair or generic inspection", 3: "Photovoltaic, SPDA, fire, automation, or medium voltage" }
        },
        faq: {
          kicker: "Common questions", title: "Before requesting a proposal", intro: "The initial contact is a scope screening, not free remote dimensioning.",
          items: {
            0: { q: "Is the ART included?", a: "The proposal identifies the design ART and applicable fee separately or as part of the total. It covers only the activities effectively contracted and developed by Adrian." },
            1: { q: "Do you also install the electrical system?", a: "No. The initial service is design only. The installer remains responsible for execution and must follow the documentation, applicable rules, and recorded changes." },
            2: { q: "Can you price by square metre?", a: "Area alone does not define effort or responsibility. The estimate also considers boards, levels, loads, compatibility, input quality, visits, and revisions." },
            3: { q: "Do you take urgent projects?", a: "No. Availability is intentionally controlled at one active project, and the schedule is confirmed only after the scope has been estimated." }
          }
        },
        cta: { kicker: "Scope review", title: "Send the basic information about your project.", desc: "Include the address or neighbourhood in Jundiaí, property type, current stage, available architectural files, planned loads, and desired date. You will receive a compatibility and availability response by the next business day.", button: "Request review by email", legal: "Email opens with a suggested subject. Sending information does not create a contract or technical responsibility." }
      },
      partners: {
        meta: { title: "Electrical Design for Architects in Jundiaí — Adrian Batista", description: "Residential electrical design support for architects, interior designers, civil engineers, and small builders in Jundiaí." },
        hero: { eyebrow: "For architects, designers, engineers, and builders", title: "Electrical compatibility that enters your design workflow.", lead: "Residential electrical design with defined inputs, review milestones, documented interfaces, and a handoff that the execution team can interpret." },
        collaboration: {
          kicker: "Partnership model", title: "Support without hiding responsibilities.", intro: "Adrian works as the electrical designer for the contracted scope. Architecture, execution, and approvals remain with their respective responsible parties.",
          items: { 0: { title: "Structured input", desc: "Architecture, equipment schedule, usage decisions, and project constraints are checked before production starts." }, 1: { title: "Compatibility milestones", desc: "Electrical decisions return at agreed moments, reducing uncontrolled changes at the end of the project." }, 2: { title: "Traceable handoff", desc: "Files, revisions, assumptions, and pending decisions are identified for the coordinator and installer." } }
        },
        inputs: { kicker: "Project intake", title: "Information that avoids rework", intro: "The exact list varies by property, but the partner should expect to provide:", items: { 0: "Stable architectural plan in agreed format", 1: "Room use and furniture/layout references", 2: "Equipment and relevant load schedule", 3: "Utility, condominium, and project constraints", 4: "Expected compatibility milestones", 5: "Named person responsible for consolidating decisions" } },
        process: { kicker: "Coordination", title: "Four explicit handoff points", intro: "A lean workflow designed for low volume and careful review.", items: { 0: { title: "Feasibility", desc: "Scope, schedule, files, interfaces, and responsibility boundaries are checked." }, 1: { title: "Electrical concept", desc: "Boards, principal loads, point strategy, and open decisions are aligned." }, 2: { title: "Technical development", desc: "Circuits, dimensions, protection, diagrams, and notes are developed and checked." }, 3: { title: "Issue for execution", desc: "Approved revision, design ART, file register, and delivery orientation are issued." } } },
        boundaries: { kicker: "Commercial clarity", title: "What the partnership does — and does not — transfer", intro: "No hidden commission or informal transfer of technical responsibility.", includedTitle: "Working agreement", included: { 0: "Named technical contacts", 1: "Defined review allowance and milestones", 2: "Revision and decision register", 3: "Direct technical communication" }, excludedTitle: "Requires separate scope", excluded: { 0: "Site supervision or installation management", 1: "As-built survey or existing-system diagnosis", 2: "Editable source-file rights by default", 3: "External approvals or other engineering disciplines" } },
        faq: { kicker: "Partner questions", title: "Operational points", intro: "The first conversation is used to compare workflows, not to force exclusivity.", items: { 0: { q: "Which drawing format do you use?", a: "Development is planned in AutoCAD. Input and output formats, layers, standards, and source-file delivery are agreed in the proposal." }, 1: { q: "Can the client speak directly with the electrical designer?", a: "Yes, when the communication route is agreed with the project coordinator and decisions are recorded for the whole team." }, 2: { q: "Do you accept recurring work?", a: "Potentially, but capacity starts at one active project. Recurrence is accepted only after actual effort and schedule compatibility are measured." }, 3: { q: "Do you pay referral commissions?", a: "No commission is assumed. Any future commercial arrangement would require transparent ethical, contractual, and tax review." } } },
        cta: { kicker: "Technical conversation", title: "Compare workflows before the next project starts.", desc: "Send one representative project type, the files you normally produce, expected milestones, and the main execution problem you want the electrical design to solve.", button: "Discuss a partnership by email", legal: "A conversation does not reserve capacity. Availability is confirmed for each proposed project." }
      },
      construction: {
        meta: { title: "Electrical Design for Construction and Renovation in Jundiaí", description: "Electrical design for homeowners planning a house, apartment renovation, or major residential renovation in Jundiaí." },
        hero: { eyebrow: "For homeowners planning construction or renovation", title: "Electrical decisions documented before the wall closes.", lead: "A residential electrical design turns room use, appliances, and future needs into circuits, protection, boards, diagrams, and instructions for the installer." },
        decisions: { kicker: "Before execution", title: "The design connects daily use to technical decisions.", intro: "It is most useful when architecture and equipment choices are stable enough to avoid designing from assumptions.", items: { 0: { title: "How each room will be used", desc: "Furniture, work areas, lighting, outlets, and equipment affect point locations and circuit organization." }, 1: { title: "Which loads are planned", desc: "Showers, ovens, cooktops, air conditioning, pumps, and other equipment need known technical data." }, 2: { title: "What may change later", desc: "Reasonable future needs can be recorded in the briefing; unlimited undefined expansion cannot be promised." } } },
        inputs: { kicker: "What to prepare", title: "A useful initial package", intro: "You do not need to solve the electrical design before contacting the engineer. You do need to provide reliable information.", items: { 0: "Architectural floor plan with dimensions", 1: "Property address and construction/renovation type", 2: "Room use and furniture layout", 3: "Equipment list with power data when available", 4: "Condominium or utility constraints", 5: "Current stage and realistic execution date" } },
        process: { kicker: "From briefing to delivery", title: "Decisions are closed in stages", intro: "Changes remain possible, but their impact on time and scope is recorded.", items: { 0: { title: "Initial screening", desc: "The available information is checked to confirm whether the project fits the initial service." }, 1: { title: "Briefing", desc: "Use of spaces, equipment, constraints, and responsible contacts are consolidated." }, 2: { title: "Design and revision", desc: "Technical documents are developed and reviewed at the agreed milestones." }, 3: { title: "Delivery", desc: "The approved set and design ART are explained for transfer to the installer." } } },
        boundaries: { kicker: "Who is responsible for what", title: "A design guides execution; it does not replace it.", intro: "The owner must keep architecture and equipment decisions current and ensure the installer works from the approved revision.", includedTitle: "Design responsibility", included: { 0: "Dimensioning within the contracted assumptions", 1: "Technical documentation and identified revisions", 2: "Design ART", 3: "Delivery orientation" }, excludedTitle: "Owner and installer responsibilities", excluded: { 0: "Accurate input and change communication", 1: "Safe and compliant physical execution", 2: "Recording site changes before implementation", 3: "Hiring separate inspections or supervision when needed" } },
        faq: { kicker: "Homeowner questions", title: "What usually needs clarification", intro: "The proposal resolves the specific version of these questions for your property.", items: { 0: { q: "Is an architectural plan required?", a: "For the initial offer, a stable digital plan is normally required. Designing over incomplete or constantly changing architecture increases rework and risk." }, 1: { q: "Can the electrician decide the details on site?", a: "The installer can identify practical constraints, but technical changes should be evaluated and recorded before execution. Improvisation can invalidate assumptions and split responsibility." }, 2: { q: "Does the design include materials?", a: "Technical specifications are included according to scope. A detailed purchasing list or quantity takeoff is included only when explicitly contracted." }, 3: { q: "Can you design an apartment renovation?", a: "Potentially, after screening. Existing installations may require survey, inspection, or measurements outside the initial design-only offer." } } },
        cta: { kicker: "Start with the project stage", title: "Describe what will be built or renovated.", desc: "Send the location, property type, approximate area, current stage, architectural file availability, main equipment, and intended construction date.", button: "Send project information", legal: "The first response confirms fit and availability. Price and schedule require a defined scope." }
      },
      loads: {
        meta: { title: "Electrical Design for New Residential Loads in Jundiaí", description: "Technical screening and electrical design for planned new residential loads, circuits, and capacity changes in Jundiaí." },
        hero: { eyebrow: "For planned new electrical loads", title: "A new load starts with installation capacity, not with the outlet.", lead: "Air conditioning, electric showers, cooktops, pumps, chargers, and other equipment may affect circuits, protection, boards, demand, and the service entrance. The first step is technical screening." },
        cases: { kicker: "Typical triggers", title: "When a new circuit may not be the whole answer", intro: "The examples indicate situations for evaluation; they do not mean every case fits the initial offer.", items: { 0: { title: "Climate and heating", desc: "Air conditioning, electric showers, heaters, and heat pumps can change simultaneous demand and protection requirements." }, 1: { title: "Kitchen and service equipment", desc: "Cooktops, ovens, dryers, pumps, and workshops may require dedicated circuits and revised distribution." }, 2: { title: "Mobility and future use", desc: "Electric-vehicle charging or planned expansion requires equipment data, usage assumptions, and possibly utility interface." } } },
        screening: { kicker: "Technical screening", title: "Information needed before promising a solution", intro: "An existing installation cannot be declared adequate from a photo or chat message alone.", items: { 0: "Equipment technical data and intended use", 1: "Property address and utility service information", 2: "Available diagrams or previous designs", 3: "Switchboard and service-entrance information", 4: "Age and known history of the installation", 5: "Access conditions for a possible site survey" } },
        process: { kicker: "Decision path", title: "Screen, verify, then design", intro: "Some cases proceed to design; others first require a separate field survey or a different specialist.", items: { 0: { title: "Remote pre-screening", desc: "Documents and equipment data establish whether the request is technically and operationally compatible." }, 1: { title: "Evidence decision", desc: "If existing conditions cannot be verified, a survey, inspection, or measurement scope is proposed separately." }, 2: { title: "Electrical design", desc: "Accepted cases receive the required circuit, protection, distribution, and interface documentation." }, 3: { title: "Recorded handoff", desc: "Assumptions, limits, design ART, and execution instructions are delivered without guaranteeing unknown existing conditions." } } },
        boundaries: { kicker: "Safety boundary", title: "No diagnosis by guesswork.", intro: "The service is for planned changes, not emergency repair or a generic certificate for an existing installation.", includedTitle: "May fit after screening", included: { 0: "New dedicated residential circuits", 1: "Distribution and protection changes", 2: "Demand and service-interface review", 3: "Technical documentation for planned work" }, excludedTitle: "Not the initial service", excluded: { 0: "Emergency troubleshooting or repair", 1: "Compliance statement without inspection", 2: "Photovoltaic or medium-voltage design", 3: "EV charger installation or utility approval by default" } },
        faq: { kicker: "Screening questions", title: "Important distinctions", intro: "The safe answer often depends on information that is not visible remotely.", items: { 0: { q: "Can you confirm capacity from a switchboard photo?", a: "No. A photo can support screening, but it does not prove conductor conditions, connections, service capacity, grounding, demand, or the full installation." }, 1: { q: "Do you install the new equipment?", a: "No. The initial offer covers electrical design. Installation, testing, commissioning, and utility procedures require their own responsible parties and scope." }, 2: { q: "Is an on-site visit always necessary?", a: "Not always. It becomes necessary when reliable documents do not establish the existing conditions needed for a responsible design." }, 3: { q: "Do you handle electric-vehicle chargers?", a: "The planned load can be screened, but detailed charger design, installation, utility interface, or condominium approval is accepted only under a specifically validated scope." } } },
        cta: { kicker: "Capacity screening", title: "Send the equipment data and what is known about the installation.", desc: "Include the property location, equipment model/power, intended use, available design or diagram, switchboard information, and desired implementation date.", button: "Request technical screening", legal: "Remote screening does not certify the existing installation. A separate site survey may be required before a proposal." }
      }
    }
  },
  pt: {
    serviceCommon: {
      nav: { home: "Início", overview: "Serviço", audience: "Para quem", process: "Processo", contact: "Contato" },
      breadcrumb: { services: "Serviços", residential: "Projetos elétricos residenciais" },
      credential: { label: "Identificação profissional", status: "Disponibilidade controlada", title: "Engenheiro Eletricista", creaLabel: "CREA-SP", creaValue: "5071811903", baseLabel: "Base", baseValue: "Jundiaí / SP", scopeLabel: "Escopo inicial", scopeValue: "Somente projeto", deliveryLabel: "Formato", deliveryValue: "Documentação técnica + ART de projeto" },
      actions: { scope: "Solicitar análise de escopo", scenarios: "Escolher meu cenário", general: "Ver o serviço geral" },
      footer: { tagline: "Projeto elétrico residencial com escopo definido, decisões documentadas e responsabilidade técnica." }
    },
    residentialService: {
      general: {
        meta: { title: "Projeto Elétrico Residencial em Jundiaí — Adrian Batista", description: "Projeto elétrico residencial para construção e reforma em Jundiaí, com circuitos, cargas, proteções, documentação e ART de projeto." },
        hero: { eyebrow: "Projeto elétrico residencial · Jundiaí / SP", title: "Projeto claro para uma execução sem improviso.", lead: "Planejamento de cargas, circuitos, condutores, proteções e quadros, entregue como documentação técnica para a equipe de instalação e acompanhado de ART de projeto." },
        audience: { kicker: "Escolha o caminho correto", title: "Decisões diferentes exigem pontos de partida diferentes.", intro: "Selecione a página mais próxima da sua situação. Cada versão explica entradas, responsabilidades e próximo passo sem alterar o rigor técnico.", partner: { title: "Arquitetos e profissionais da construção", desc: "Marcos de compatibilização, documentos de entrada, entrega e comunicação com a equipe de projeto.", label: "Parceria profissional" }, construction: { title: "Construção nova ou reforma integral", desc: "O que decidir antes da execução, o que o projeto contém e como as alterações são controladas.", label: "Proprietário em planejamento" }, loads: { title: "Novas cargas planejadas", desc: "Triagem técnica para equipamentos que podem exigir novos circuitos, proteções ou revisão de capacidade.", label: "Capacidade e novos circuitos" } },
        deliverables: { kicker: "Saída técnica", title: "O que o projeto organiza", intro: "O conjunto final é definido na proposta. Os itens abaixo formam o escopo de referência para uma residência de baixa complexidade com arquitetura estável.", items: { 0: { title: "Pontos e circuitos", desc: "Distribuição dos pontos elétricos e agrupamento de circuitos coerentes com o uso aprovado de cada ambiente." }, 1: { title: "Quadro de cargas", desc: "Cargas organizadas, hipóteses de demanda, identificação de circuitos e informações dos quadros." }, 2: { title: "Condutores e proteções", desc: "Dimensionamento técnico de condutores e dispositivos de proteção conforme os critérios aplicáveis ao projeto." }, 3: { title: "Diagramas", desc: "Diagramas unifilares e detalhes necessários para interpretar o projeto durante a execução." }, 4: { title: "Notas técnicas", desc: "Especificações, premissas e orientações de execução para que as decisões não fiquem implícitas." }, 5: { title: "ART de projeto", desc: "Registro da responsabilidade técnica de Adrian pelas atividades efetivamente contratadas e desenvolvidas." } } },
        process: { kicker: "Fluxo de trabalho", title: "Uma sequência controlada antes do desenho", intro: "O desenvolvimento começa depois do alinhamento de escopo, entradas, agenda, contrato e responsabilidade técnica.", items: { 0: { title: "Triagem de escopo", desc: "Tipo de imóvel, estágio, arquivos de arquitetura, localização, cargas e decisões esperadas." }, 1: { title: "Proposta e entradas", desc: "Entregáveis, exclusões, prazo, revisões, taxas e documentos necessários são formalizados." }, 2: { title: "Projeto e revisão", desc: "Desenvolvimento técnico em AutoCAD, verificações internas e marcos definidos de compatibilização." }, 3: { title: "Entrega e orientação", desc: "Arquivos finais, ART de projeto, premissas registradas e reunião de orientação para a entrega." } } },
        boundaries: { kicker: "Limites de responsabilidade", title: "Projeto e execução são serviços diferentes.", intro: "A página não oferece emergência, assinatura isolada ou promessa de aprovação sem análise.", includedTitle: "Oferta inicial", included: { 0: "Projeto residencial com entradas definidas", 1: "Documentação técnica para execução", 2: "ART de projeto dentro do escopo contratado", 3: "Um projeto ativo por vez" }, excludedTitle: "Não incluído por padrão", excluded: { 0: "Mão de obra ou compra de materiais", 1: "Responsabilidade pela execução de terceiros", 2: "Reparo emergencial ou inspeção genérica", 3: "Fotovoltaico, SPDA, incêndio, automação ou média tensão" } },
        faq: { kicker: "Dúvidas frequentes", title: "Antes de solicitar uma proposta", intro: "O primeiro contato é uma triagem de escopo, não dimensionamento remoto gratuito.", items: { 0: { q: "A ART está incluída?", a: "A proposta identifica a ART de projeto e a taxa aplicável separadamente ou dentro do total. Ela cobre somente as atividades efetivamente contratadas e desenvolvidas por Adrian." }, 1: { q: "Você também executa a instalação?", a: "Não. A oferta inicial é somente projeto. O executor permanece responsável pela instalação e deve seguir a documentação, as regras aplicáveis e as alterações registradas." }, 2: { q: "É possível cobrar por metro quadrado?", a: "A área isoladamente não define esforço ou responsabilidade. A estimativa também considera quadros, pavimentos, cargas, compatibilização, qualidade das entradas, visitas e revisões." }, 3: { q: "Você aceita projetos urgentes?", a: "Não. A disponibilidade é controlada em um projeto ativo, e o prazo só é confirmado depois da estimativa de escopo." } } },
        cta: { kicker: "Análise de escopo", title: "Envie as informações básicas do seu projeto.", desc: "Inclua endereço ou bairro em Jundiaí, tipo de imóvel, estágio atual, arquivos de arquitetura disponíveis, cargas planejadas e data desejada. A resposta de compatibilidade e disponibilidade ocorre até o próximo dia útil.", button: "Solicitar análise por e-mail", legal: "O e-mail abre com um assunto sugerido. O envio de informações não cria contrato nem responsabilidade técnica." }
      },
      partners: {
        meta: { title: "Projetos Elétricos para Arquitetos em Jundiaí — Adrian Batista", description: "Apoio em projetos elétricos residenciais para arquitetos, designers, engenheiros civis e pequenas construtoras de Jundiaí." },
        hero: { eyebrow: "Para arquitetos, designers, engenheiros e construtoras", title: "Compatibilização elétrica que entra no fluxo do seu projeto.", lead: "Projeto elétrico residencial com entradas definidas, marcos de revisão, interfaces documentadas e uma entrega que a equipe de execução consegue interpretar." },
        collaboration: { kicker: "Modelo de parceria", title: "Apoio sem ocultar responsabilidades.", intro: "Adrian atua como projetista elétrico no escopo contratado. Arquitetura, execução e aprovações permanecem com seus respectivos responsáveis.", items: { 0: { title: "Entrada estruturada", desc: "Arquitetura, relação de equipamentos, decisões de uso e restrições são verificadas antes da produção." }, 1: { title: "Marcos de compatibilização", desc: "As decisões elétricas retornam em momentos combinados, reduzindo alterações descontroladas ao final." }, 2: { title: "Entrega rastreável", desc: "Arquivos, revisões, premissas e decisões pendentes são identificados para o coordenador e o executor." } } },
        inputs: { kicker: "Entrada do projeto", title: "Informações que evitam retrabalho", intro: "A lista exata varia conforme o imóvel, mas o parceiro deve prever:", items: { 0: "Planta arquitetônica estável no formato combinado", 1: "Uso dos ambientes e referências de mobiliário", 2: "Relação de equipamentos e cargas relevantes", 3: "Restrições da concessionária, condomínio e projeto", 4: "Marcos esperados de compatibilização", 5: "Responsável por consolidar as decisões" } },
        process: { kicker: "Coordenação", title: "Quatro pontos explícitos de entrega", intro: "Fluxo enxuto, desenhado para baixo volume e revisão cuidadosa.", items: { 0: { title: "Viabilidade", desc: "Escopo, agenda, arquivos, interfaces e limites de responsabilidade são verificados." }, 1: { title: "Conceito elétrico", desc: "Quadros, cargas principais, estratégia de pontos e decisões abertas são alinhados." }, 2: { title: "Desenvolvimento técnico", desc: "Circuitos, dimensionamentos, proteções, diagramas e notas são desenvolvidos e conferidos." }, 3: { title: "Emissão para execução", desc: "Revisão aprovada, ART de projeto, registro de arquivos e orientação de entrega são emitidos." } } },
        boundaries: { kicker: "Clareza comercial", title: "O que a parceria transfere — e o que não transfere", intro: "Sem comissão oculta ou transferência informal de responsabilidade técnica.", includedTitle: "Acordo de trabalho", included: { 0: "Contatos técnicos nomeados", 1: "Quantidade de revisões e marcos definidos", 2: "Registro de revisões e decisões", 3: "Comunicação técnica direta" }, excludedTitle: "Exige escopo separado", excluded: { 0: "Acompanhamento ou gestão da instalação", 1: "Levantamento cadastral ou diagnóstico do existente", 2: "Direito aos arquivos editáveis por padrão", 3: "Aprovações externas ou outras disciplinas" } },
        faq: { kicker: "Dúvidas do parceiro", title: "Pontos operacionais", intro: "A primeira conversa compara processos; não exige exclusividade.", items: { 0: { q: "Qual formato de desenho você utiliza?", a: "O desenvolvimento está planejado em AutoCAD. Formatos de entrada e saída, layers, padrões e entrega de fontes são combinados na proposta." }, 1: { q: "O cliente pode falar diretamente com o projetista elétrico?", a: "Sim, quando a rota de comunicação estiver combinada com a coordenação e as decisões forem registradas para toda a equipe." }, 2: { q: "Você aceita demanda recorrente?", a: "Potencialmente, mas a capacidade começa em um projeto ativo. Recorrência só será aceita depois de medir esforço real e compatibilidade de agenda." }, 3: { q: "Você paga comissão por indicação?", a: "Não há comissão presumida. Qualquer arranjo comercial futuro exigiria avaliação ética, contratual e fiscal transparente." } } },
        cta: { kicker: "Conversa técnica", title: "Compare os fluxos antes de o próximo projeto começar.", desc: "Envie uma tipologia representativa, os arquivos que sua equipe normalmente produz, os marcos esperados e o principal problema de execução que o projeto elétrico deve resolver.", button: "Conversar sobre parceria por e-mail", legal: "A conversa não reserva capacidade. A disponibilidade é confirmada para cada projeto proposto." }
      },
      construction: {
        meta: { title: "Projeto Elétrico para Construção e Reforma em Jundiaí", description: "Projeto elétrico para proprietários planejando casa, reforma de apartamento ou reforma residencial integral em Jundiaí." },
        hero: { eyebrow: "Para proprietários planejando construção ou reforma", title: "Decisões elétricas documentadas antes de fechar a parede.", lead: "O projeto elétrico residencial transforma o uso dos ambientes, os equipamentos e as necessidades futuras em circuitos, proteções, quadros, diagramas e orientações para o executor." },
        decisions: { kicker: "Antes da execução", title: "O projeto conecta o uso diário às decisões técnicas.", intro: "Ele é mais útil quando a arquitetura e as escolhas de equipamentos estão estáveis o suficiente para não projetar com suposições.", items: { 0: { title: "Como cada ambiente será usado", desc: "Mobiliário, áreas de trabalho, iluminação, tomadas e equipamentos afetam pontos e organização dos circuitos." }, 1: { title: "Quais cargas estão previstas", desc: "Chuveiros, fornos, cooktops, ar-condicionado, bombas e outros equipamentos precisam de dados técnicos conhecidos." }, 2: { title: "O que pode mudar no futuro", desc: "Necessidades futuras razoáveis podem entrar no briefing; expansão ilimitada e indefinida não pode ser prometida." } } },
        inputs: { kicker: "O que preparar", title: "Um pacote inicial útil", intro: "Você não precisa resolver a elétrica antes de falar com o engenheiro. Precisa fornecer informações confiáveis.", items: { 0: "Planta arquitetônica cotada", 1: "Endereço e tipo de construção ou reforma", 2: "Uso dos ambientes e layout de mobiliário", 3: "Lista de equipamentos com potência disponível", 4: "Restrições do condomínio ou concessionária", 5: "Estágio atual e data realista da execução" } },
        process: { kicker: "Do briefing à entrega", title: "As decisões são fechadas por etapas", intro: "Alterações continuam possíveis, mas seu impacto em prazo e escopo é registrado.", items: { 0: { title: "Triagem inicial", desc: "As informações disponíveis são verificadas para confirmar se o trabalho cabe na oferta inicial." }, 1: { title: "Briefing", desc: "Uso dos ambientes, equipamentos, restrições e responsáveis são consolidados." }, 2: { title: "Projeto e revisão", desc: "A documentação técnica é desenvolvida e revisada nos marcos combinados." }, 3: { title: "Entrega", desc: "O conjunto aprovado e a ART de projeto são explicados para transferência ao executor." } } },
        boundaries: { kicker: "Quem responde pelo quê", title: "O projeto orienta a execução; não a substitui.", intro: "O proprietário deve manter atualizadas as decisões de arquitetura e equipamentos e garantir que o executor use a revisão aprovada.", includedTitle: "Responsabilidade do projeto", included: { 0: "Dimensionamento dentro das premissas contratadas", 1: "Documentação técnica e revisões identificadas", 2: "ART de projeto", 3: "Orientação de entrega" }, excludedTitle: "Responsabilidades do cliente e executor", excluded: { 0: "Informações corretas e comunicação de mudanças", 1: "Execução física segura e conforme", 2: "Registro de alterações antes de executá-las", 3: "Contratação separada de inspeção ou acompanhamento" } },
        faq: { kicker: "Dúvidas do proprietário", title: "O que normalmente precisa ser esclarecido", intro: "A proposta resolve a versão específica dessas perguntas para o seu imóvel.", items: { 0: { q: "Preciso ter um projeto arquitetônico?", a: "Para a oferta inicial, normalmente é necessária uma planta digital estável. Projetar sobre arquitetura incompleta ou em mudança contínua aumenta retrabalho e risco." }, 1: { q: "O eletricista pode decidir os detalhes na obra?", a: "O executor pode identificar restrições práticas, mas alterações técnicas devem ser avaliadas e registradas antes da execução. Improvisos podem invalidar premissas e dividir responsabilidades." }, 2: { q: "O projeto inclui os materiais?", a: "As especificações técnicas entram conforme o escopo. Lista detalhada de compra ou quantitativo só é incluído quando expressamente contratado." }, 3: { q: "Você projeta reforma de apartamento?", a: "Potencialmente, após triagem. Instalações existentes podem exigir levantamento, inspeção ou medições fora da oferta inicial de projeto." } } },
        cta: { kicker: "Comece pelo estágio da obra", title: "Descreva o que será construído ou reformado.", desc: "Envie localização, tipo de imóvel, área aproximada, estágio atual, disponibilidade da arquitetura, principais equipamentos e data prevista de obra.", button: "Enviar informações do projeto", legal: "A primeira resposta confirma aderência e disponibilidade. Preço e prazo exigem escopo definido." }
      },
      loads: {
        meta: { title: "Projeto Elétrico para Novas Cargas Residenciais em Jundiaí", description: "Triagem técnica e projeto elétrico para novas cargas, circuitos e alterações de capacidade em residências de Jundiaí." },
        hero: { eyebrow: "Para novas cargas elétricas planejadas", title: "Nova carga começa pela capacidade da instalação, não pela tomada.", lead: "Ar-condicionado, chuveiros, cooktops, bombas, carregadores e outros equipamentos podem afetar circuitos, proteções, quadros, demanda e entrada de energia. O primeiro passo é a triagem técnica." },
        cases: { kicker: "Gatilhos comuns", title: "Quando um circuito novo pode não ser a resposta completa", intro: "Os exemplos indicam situações para avaliação; não significam que todos os casos cabem na oferta inicial.", items: { 0: { title: "Climatização e aquecimento", desc: "Ar-condicionado, chuveiros, aquecedores e bombas de calor podem alterar demanda simultânea e requisitos de proteção." }, 1: { title: "Cozinha e área de serviço", desc: "Cooktops, fornos, secadoras, bombas e oficinas podem exigir circuitos dedicados e redistribuição." }, 2: { title: "Mobilidade e uso futuro", desc: "Recarga de veículo elétrico ou expansão planejada exige dados do equipamento, hipóteses de uso e possível interface com a concessionária." } } },
        screening: { kicker: "Triagem técnica", title: "Informações necessárias antes de prometer uma solução", intro: "Uma instalação existente não pode ser declarada adequada por foto ou mensagem.", items: { 0: "Dados técnicos do equipamento e uso previsto", 1: "Endereço e informações do fornecimento", 2: "Diagramas ou projetos anteriores disponíveis", 3: "Informações do quadro e entrada de energia", 4: "Idade e histórico conhecido da instalação", 5: "Condições de acesso para possível visita" } },
        process: { kicker: "Caminho de decisão", title: "Triar, verificar e então projetar", intro: "Alguns casos seguem para projeto; outros exigem primeiro levantamento de campo separado ou outro especialista.", items: { 0: { title: "Pré-triagem remota", desc: "Documentos e dados do equipamento indicam se o pedido é compatível técnica e operacionalmente." }, 1: { title: "Decisão de evidências", desc: "Se o existente não puder ser verificado, levantamento, inspeção ou medição são propostos separadamente." }, 2: { title: "Projeto elétrico", desc: "Casos aceitos recebem documentação de circuitos, proteções, distribuição e interfaces necessárias." }, 3: { title: "Entrega registrada", desc: "Premissas, limites, ART de projeto e orientações são entregues sem garantir condições existentes desconhecidas." } } },
        boundaries: { kicker: "Limite de segurança", title: "Sem diagnóstico por suposição.", intro: "O serviço trata de alterações planejadas, não de reparo emergencial ou atestado genérico da instalação existente.", includedTitle: "Pode caber após triagem", included: { 0: "Novos circuitos residenciais dedicados", 1: "Alterações de distribuição e proteção", 2: "Revisão de demanda e interface de entrada", 3: "Documentação técnica para a alteração planejada" }, excludedTitle: "Fora da oferta inicial", excluded: { 0: "Diagnóstico emergencial ou reparo", 1: "Declaração de conformidade sem inspeção", 2: "Projeto fotovoltaico ou média tensão", 3: "Instalação de carregador ou aprovação externa por padrão" } },
        faq: { kicker: "Dúvidas de triagem", title: "Distinções importantes", intro: "A resposta segura frequentemente depende de informações invisíveis à distância.", items: { 0: { q: "É possível confirmar a capacidade por uma foto do quadro?", a: "Não. A foto pode apoiar a triagem, mas não comprova condutores, conexões, capacidade do fornecimento, aterramento, demanda ou toda a instalação." }, 1: { q: "Você instala o equipamento novo?", a: "Não. A oferta inicial cobre projeto elétrico. Instalação, testes, comissionamento e procedimentos com a concessionária exigem responsáveis e escopos próprios." }, 2: { q: "A visita ao local é sempre necessária?", a: "Nem sempre. Ela se torna necessária quando documentos confiáveis não demonstram as condições existentes exigidas para projetar com responsabilidade." }, 3: { q: "Você atende carregador de veículo elétrico?", a: "A carga planejada pode ser triada, mas projeto específico, instalação, interface com concessionária ou aprovação de condomínio só entram em escopo próprio e validado." } } },
        cta: { kicker: "Triagem de capacidade", title: "Envie os dados do equipamento e o que se sabe da instalação.", desc: "Inclua localização, modelo e potência do equipamento, uso previsto, projeto ou diagrama disponível, informações do quadro e data desejada de implantação.", button: "Solicitar triagem técnica", legal: "A triagem remota não certifica a instalação existente. Uma visita separada pode ser necessária antes da proposta." }
      }
    }
  }
});
