/** Translations specific to the Background Remover project. */
export default {
  en: { project: { backgroundRemover: {
    category: "Software Engineering",
    meta: { title: "Background Remover — Adrian Felipe Nogueira Batista", description: "A visual interface for uploading an image, previewing a transparent-background result, and downloading the output." },
    title: "Background Remover", subtitle: "Upload an image, review the transparent-background preview, and download the result.",
    tags: { 0: "Web App", 1: "Image Processing", 2: "Interface Prototype" },
    workspace: { status: "Prototype interface", note: "Local preview only. No image is uploaded or processed." },
    upload: { kicker: "Input", title: "Source image", action: "Drop image here", hint: "or select a PNG, JPG, WEBP file", replace: "Drop another image to replace", fileLabel: "Selected file", invalid: "Choose a valid image file." },
    result: { kicker: "Output", title: "Transparent result", placeholder: "Transparent preview area", detail: "The processing service is not connected yet.", status: "Waiting for an image", download: "Download PNG" },
    articleLink: "Read how background removal works",
    article: {
      breadcrumb: "Article", meta: { title: "How Background Removal Works — Adrian Felipe Nogueira Batista", description: "An overview of image background removal, its processing stages, and how to use this interface." },
      title: "How Background Removal Works", subtitle: "A practical overview of image segmentation and the workflow proposed by this tool.", tags: { 0: "Guide", 1: "Image Processing", 2: "Web App" },
      overview: { title: "What is background removal?", p1: "Background removal separates the primary subject of an image from the surrounding pixels. The output normally preserves the subject and replaces the original background with transparency, making the image easier to reuse in documents, product catalogs, or compositions.", p2: "The task is more than a simple color replacement. A useful result has to preserve boundaries around hair, fabric, transparent objects, and fine details while avoiding unwanted portions of the background." },
      process: { title: "Typical processing stages", p1: "A removal service usually receives an image, identifies the foreground subject, and produces a mask. Each mask pixel represents how strongly the original pixel belongs to the subject. The service then applies this mask as the image alpha channel, creating a transparent-background output.", p2: "The visual quality depends on the model, input resolution, subject contrast, and details near the boundary. A final refinement step may soften edges and reduce artifacts before the PNG or WebP result is generated.", steps: { 0: { title: "Input", text: "Validate the selected file and prepare its pixels for processing." }, 1: { title: "Segmentation", text: "Estimate which pixels belong to the foreground subject." }, 2: { title: "Mask", text: "Convert the foreground estimate into an alpha mask with refined edges." }, 3: { title: "Output", text: "Apply the mask and export an image format that supports transparency." } } },
      usage: { title: "How to use this interface", intro: "The project currently provides the visual workflow only; no image is sent or converted yet.", steps: { 0: "Select the upload area and choose an image. The file chooser filters for image formats.", 1: "In a connected version, the chosen file would be sent to the removal service.", 2: "The result panel would show the transparent output over the checkerboard surface.", 3: "Once an output is available, the download button would provide the processed image." }, outro: "Keeping the interface separate from the processing service makes it possible to connect a local model, a server-side API, or another approved image-processing workflow later." }, openTool: "Open Background Remover"
    }
  } } },
  pt: { project: { backgroundRemover: {
    category: "Engenharia de Software",
    meta: { title: "Removedor de Fundo — Adrian Felipe Nogueira Batista", description: "Uma interface visual para enviar uma imagem, visualizar o resultado com fundo transparente e baixar o arquivo." },
    title: "Removedor de Fundo", subtitle: "Envie uma imagem, visualize o resultado com fundo transparente e baixe o arquivo.",
    tags: { 0: "Web App", 1: "Processamento de Imagens", 2: "Protótipo de Interface" },
    workspace: { status: "Interface protótipo", note: "Prévia local apenas. Nenhuma imagem é enviada ou processada." },
    upload: { kicker: "Entrada", title: "Imagem de origem", action: "Solte a imagem aqui", hint: "ou selecione um arquivo PNG, JPG, WEBP", replace: "Solte outra imagem para substituir", fileLabel: "Arquivo selecionado", invalid: "Escolha um arquivo de imagem válido." },
    result: { kicker: "Saída", title: "Resultado transparente", placeholder: "Área de prévia transparente", detail: "O serviço de processamento ainda não está conectado.", status: "Aguardando uma imagem", download: "Baixar PNG" },
    articleLink: "Entenda como funciona a remoção de fundo",
    article: {
      breadcrumb: "Artigo", meta: { title: "Como Funciona a Remoção de Fundo — Adrian Felipe Nogueira Batista", description: "Uma visão geral sobre remoção de fundo em imagens, suas etapas de processamento e como utilizar esta interface." },
      title: "Como Funciona a Remoção de Fundo", subtitle: "Uma visão prática sobre segmentação de imagens e o fluxo proposto por esta ferramenta.", tags: { 0: "Guia", 1: "Processamento de Imagens", 2: "Web App" },
      overview: { title: "O que é remoção de fundo?", p1: "A remoção de fundo separa o assunto principal de uma imagem dos pixels ao redor. O resultado normalmente preserva o assunto e substitui o fundo original por transparência, tornando a imagem mais fácil de reutilizar em documentos, catálogos de produtos ou composições.", p2: "A tarefa vai além da simples troca de uma cor. Um resultado útil precisa preservar contornos de cabelos, tecidos, objetos transparentes e detalhes finos, sem incluir partes indesejadas do fundo." },
      process: { title: "Etapas típicas do processamento", p1: "Um serviço de remoção normalmente recebe a imagem, identifica o assunto em primeiro plano e produz uma máscara. Cada pixel da máscara representa o quanto o pixel original pertence ao assunto. Em seguida, o serviço aplica essa máscara como canal alfa da imagem, criando um resultado com fundo transparente.", p2: "A qualidade visual depende do modelo, da resolução da imagem de entrada, do contraste do assunto e dos detalhes próximos ao contorno. Uma etapa final de refinamento pode suavizar as bordas e reduzir artefatos antes de gerar o resultado em PNG ou WebP.", steps: { 0: { title: "Entrada", text: "Validar o arquivo selecionado e preparar seus pixels para o processamento." }, 1: { title: "Segmentação", text: "Estimar quais pixels pertencem ao assunto em primeiro plano." }, 2: { title: "Máscara", text: "Converter a estimativa de primeiro plano em uma máscara alfa com bordas refinadas." }, 3: { title: "Saída", text: "Aplicar a máscara e exportar um formato de imagem compatível com transparência." } } },
      usage: { title: "Como utilizar esta interface", intro: "O projeto oferece atualmente apenas o fluxo visual; nenhuma imagem é enviada ou convertida ainda.", steps: { 0: "Selecione a área de envio e escolha uma imagem. O seletor de arquivos filtra formatos de imagem.", 1: "Em uma versão conectada, o arquivo escolhido seria enviado ao serviço de remoção.", 2: "O painel de resultado mostraria a saída transparente sobre a superfície quadriculada.", 3: "Quando houver um resultado disponível, o botão de download fornecerá a imagem processada." }, outro: "Manter a interface separada do serviço de processamento permite conectar posteriormente um modelo local, uma API no servidor ou outro fluxo aprovado de processamento de imagens." }, openTool: "Abrir Removedor de Fundo"
    }
  } } },
};
