/** Translations specific to the UUID Generator project. */
export default {
  en: { project: { uuidGenerator: {
    category: "Software Engineering", meta: { title: "UUID Generator — Adrian Felipe Nogueira Batista", description: "Generate standards-compliant UUIDs in the browser, with version 4 as the default." },
    title: "UUID Generator", subtitle: "Generate identifiers locally with cryptographically secure browser randomness. Version 4 is selected by default.", tags: { 0: "JavaScript", 1: "Web Tool", 2: "RFC 9562" },
    tool: { label: "Generator", version: "UUID version", count: "Quantity", generate: "Generate UUIDs", copy: "Copy", copied: "Copied", secure: "Local generation", secureNote: "No identifier is sent to a server.", v1: "Version 1 — time-based", v4: "Version 4 — random", v7: "Version 7 — time-ordered", output: "Generated UUIDs", empty: "Select a version and generate one or more UUIDs." },
    articleLink: "Read the UUID guide", article: { breadcrumb: "Article", meta: { title: "UUID: History, Motivation, Versions and Usage — Adrian Felipe Nogueira Batista", description: "A practical guide to UUIDs: why they exist, how their versions differ, and when to use them." }, title: "UUID: History, Motivation, Versions and Usage", subtitle: "A practical introduction to globally unique identifiers, their structure, and their trade-offs.", tags: { 0: "Guide", 1: "Distributed Systems", 2: "Identifiers" },
      history: { title: "Where UUIDs came from", p1: "UUID stands for Universally Unique Identifier. The format originated in the Distributed Computing Environment, where independent systems needed to name objects without a shared counter or a central coordinator. It was later standardized by the IETF; the current specification is RFC 9562, which supersedes RFC 4122.", p2: "The same 128-bit format is often called a GUID in Microsoft ecosystems. The names differ more than the underlying idea: generate an identifier locally with a collision probability low enough for practical distributed use." },
      motivation: { title: "The problem UUIDs solve", p1: "An auto-incrementing database key works well inside one database, but it requires coordination and can collide when records are created independently and later merged. UUIDs let a client, service, or offline process create an identifier before it contacts a central database.", p2: "That property is useful for event messages, public resource IDs, synchronization, import pipelines, and multi-service systems. Uniqueness is probabilistic for random versions, not mathematically guaranteed; correct systems still enforce a unique constraint where collisions would matter." },
      anatomy: { title: "Format and versions", p1: "A canonical UUID is 16 bytes written as 32 hexadecimal characters in five groups: 8-4-4-4-12. A version nibble identifies the generation layout, while variant bits identify the interoperable RFC layout.", versions: { v1: { title: "v1 · time-based", text: "Combines a timestamp, clock sequence, and node identifier. It can reveal generation time; this tool uses a random multicast node value rather than a hardware MAC address." }, v4: { title: "v4 · random", text: "Uses cryptographically secure random bytes, with the version and variant bits fixed. It is the default here because it is simple, widely supported, and does not expose a timestamp." }, v7: { title: "v7 · time-ordered", text: "Places a Unix-millisecond timestamp first, followed by random data. Its ordering improves index locality compared with v4 while retaining randomized uniqueness." } }, code: "550e8400-e29b-41d4-a716-446655440000\n^^^^^^^^^^^^ ^\n128 bits      version 4" },
      usage: { title: "Choosing and using a UUID", intro: "Use the version that follows the data and operational requirements:", steps: { 0: "Choose v4 for general-purpose opaque identifiers, especially public IDs and browser-generated values.", 1: "Choose v7 when new records are frequently indexed or sorted by creation time and timestamp disclosure is acceptable.", 2: "Avoid v1 for public identifiers unless its time metadata and node treatment are understood.", 3: "Store UUIDs in a native UUID type or a 16-byte binary column when available; use the canonical string at application boundaries." }, outro: "A UUID is an identifier, not a secret or an authorization mechanism. Do not grant access merely because somebody knows one." }, openTool: "Open UUID generator" }
  } } },
  pt: { project: { uuidGenerator: {
    category: "Engenharia de Software", meta: { title: "Gerador de UUID — Adrian Felipe Nogueira Batista", description: "Gere UUIDs compatíveis com o padrão no navegador, com a versão 4 como padrão." },
    title: "Gerador de UUID", subtitle: "Gere identificadores localmente com aleatoriedade criptograficamente segura do navegador. A versão 4 é selecionada por padrão.", tags: { 0: "JavaScript", 1: "Ferramenta Web", 2: "RFC 9562" },
    tool: { label: "Gerador", version: "Versão do UUID", count: "Quantidade", generate: "Gerar UUIDs", copy: "Copiar", copied: "Copiado", secure: "Geração local", secureNote: "Nenhum identificador é enviado para um servidor.", v1: "Versão 1 — baseada em tempo", v4: "Versão 4 — aleatória", v7: "Versão 7 — ordenada por tempo", output: "UUIDs gerados", empty: "Selecione uma versão e gere um ou mais UUIDs." },
    articleLink: "Leia o guia sobre UUID", article: { breadcrumb: "Artigo", meta: { title: "UUID: História, Motivação, Versões e Uso — Adrian Felipe Nogueira Batista", description: "Um guia prático sobre UUIDs: por que existem, como suas versões diferem e quando utilizá-las." }, title: "UUID: História, Motivação, Versões e Uso", subtitle: "Uma introdução prática a identificadores globalmente únicos, sua estrutura e suas compensações.", tags: { 0: "Guia", 1: "Sistemas Distribuídos", 2: "Identificadores" },
      history: { title: "De onde vieram os UUIDs", p1: "UUID significa Identificador Universalmente Único. O formato surgiu no Distributed Computing Environment, no qual sistemas independentes precisavam nomear objetos sem um contador compartilhado ou coordenador central. Depois foi padronizado pela IETF; a especificação atual é a RFC 9562, que substitui a RFC 4122.", p2: "O mesmo formato de 128 bits costuma ser chamado de GUID em ecossistemas Microsoft. Os nomes diferem mais que a ideia: gerar localmente um identificador com probabilidade de colisão suficientemente baixa para uso prático em sistemas distribuídos." },
      motivation: { title: "O problema que UUIDs resolvem", p1: "Uma chave incremental funciona bem dentro de um banco, mas exige coordenação e pode colidir quando registros são criados de forma independente e depois unidos. UUIDs permitem que um cliente, serviço ou processo offline crie um identificador antes de falar com um banco central.", p2: "Isso é útil para mensagens de eventos, IDs públicos de recursos, sincronização, importações e sistemas com vários serviços. A unicidade é probabilística nas versões aleatórias, não uma garantia matemática; sistemas corretos ainda aplicam uma restrição única quando uma colisão importa." },
      anatomy: { title: "Formato e versões", p1: "Um UUID canônico tem 16 bytes escritos como 32 caracteres hexadecimais em cinco grupos: 8-4-4-4-12. Um nibble de versão identifica o layout de geração e bits de variante identificam o layout RFC interoperável.", versions: { v1: { title: "v1 · baseada em tempo", text: "Combina timestamp, sequência de relógio e identificador de nó. Pode revelar o horário de geração; esta ferramenta usa um nó aleatório multicast, e não um endereço MAC." }, v4: { title: "v4 · aleatória", text: "Usa bytes aleatórios criptograficamente seguros, com os bits de versão e variante fixos. É o padrão aqui por ser simples, amplamente suportada e não expor um timestamp." }, v7: { title: "v7 · ordenada por tempo", text: "Coloca um timestamp Unix em milissegundos primeiro, seguido de dados aleatórios. Sua ordenação melhora a localidade de índices em comparação com v4 e preserva unicidade aleatória." } }, code: "550e8400-e29b-41d4-a716-446655440000\n^^^^^^^^^^^^ ^\n128 bits      versão 4" },
      usage: { title: "Escolha e uso de UUID", intro: "Use a versão que corresponde aos requisitos dos dados e da operação:", steps: { 0: "Escolha v4 para identificadores opacos de propósito geral, principalmente IDs públicos e valores gerados no navegador.", 1: "Escolha v7 quando novos registros são indexados ou ordenados frequentemente por criação e expor o timestamp é aceitável.", 2: "Evite v1 em identificadores públicos sem entender seus metadados de tempo e tratamento do nó.", 3: "Armazene UUIDs em um tipo UUID nativo ou coluna binária de 16 bytes quando disponível; use a string canônica nos limites da aplicação." }, outro: "Um UUID é um identificador, não um segredo ou mecanismo de autorização. Não conceda acesso apenas porque alguém conhece um UUID." }, openTool: "Abrir gerador de UUID" }
  } } },
};
